function CL = CL_alpha(alpha,M,alpha0,CL0,CLa)
sigmaAlpha  = @(alpha,M,alpha0)...
    (1+exp(-M.*(alpha-alpha0))+(exp(M.*(alpha+alpha0))))...
    ./...
    ((1+exp(-M.*(alpha-alpha0))).*(1+exp(M.*(alpha+alpha0))));

CL = (1-sigmaAlpha(alpha,M,alpha0))...
    .*...
    (CL0+CLa.*alpha)...
    + sigmaAlpha(alpha,M,alpha0)...
    .*...
    (2.*sign(alpha).*(sin(alpha).^2).*cos(alpha));

end